variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TERM: linux
  GIT_STRATEGY: clone

cours:
  stage: build
  only:
    - master@stepan/econometrics
  script:
    - make -C cours
    - make -C td
    - make -C examens
    - scp cours/chapitre-1.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp cours/chapitre-2.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp cours/chapitre-3.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp cours/chapitre-4.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp examens/partiel-2023.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp examens/partiel-2024.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp examens/partiel-2025.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp examens/rattrapage-2026.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp examens/correction-2023.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp examens/correction-2024.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp examens/correction-2025.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp examens/correction-rattrapage-2026.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp td/fiche-exercices.pdf /puck/www/le-mans.adjemian.eu/econometrics
    - scp -r routines/chapitre-1 /puck/www/le-mans.adjemian.eu/econometrics/codes
    - scp -r routines/chapitre-2 /puck/www/le-mans.adjemian.eu/econometrics/codes
    - scp -r routines/chapitre-3 /puck/www/le-mans.adjemian.eu/econometrics/codes
    - scp -r routines/chapitre-4 /puck/www/le-mans.adjemian.eu/econometrics/codes
    - scp -r pgf /puck/www/le-mans.adjemian.eu/econometrics
    - scp -r tikz /puck/www/le-mans.adjemian.eu/econometrics
    - scp -r data /puck/www/le-mans.adjemian.eu/econometrics
  artifacts:
    paths:
      - cours/chapitre-1.pdf
      - cours/chapitre-2.pdf
      - cours/chapitre-3.pdf
      - cours/chapitre-4.pdf
      - td/fiche-exercices.pdf
      - examens/partiel-2023.pdf
      - examens/partiel-2024.pdf
      - examens/partiel-2025.pdf
      - examens/correction-2023.pdf
      - examens/correction-2024.pdf
      - examens/correction-2025.pdf
  tags:
    - stepan@puck