#! /bin/bash
# Update Org-Babel files
emacs --batch --script init.el --eval "
(let ((org-confirm-babel-evaluate nil))
      (dolist (file command-line-args-left)
        (with-current-buffer (find-file-noselect file)
          (org-babel-execute-buffer)
          (org-babel-tangle)
          (save-buffer))))
  " $*
